### ISSUE TITLE
Name - flags? locks? mutexes?

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/web-locks#1]
This affects types (e.g. `Flag`) and entry points (e.g. `requestFlag`)

**Comment by domenic** [comment]
Weak preference for lock or mutex since I've heard them more in these kind of concurrent-programming contexts.

https://stackoverflow.com/questions/2332765/lock-mutex-semaphore-whats-the-difference says maybe "mutex" would be better since this is "cross-process".

**Comment by inexorabletash** [comment]
Other data points:

* The shared/exclusive (a.k.a. reader/writer) aspect is unique (?) to locks. A "shared mutex" sounds crazypants.
* The thing you're requesting is a lock (...) over multiple resources. So **LockSet** would be more technically correct, unless we make up a term for that.

**Comment by inexorabletash** [comment]
I did a renaming pass to 'Lock' and it doesn't seem too bad. Renamed the repo. We'll see if this sticks.

**Comment by inexorabletash** [comment]
Resolving for now, can be re-opened if anyone complains.
