### ISSUE TITLE
SecureContext?

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/web-locks#11]
Should we restrict this via `[SecureContext]` to [secure contexts](https://w3c.github.io/webappsec-secure-contexts/#settings-object) ?

Pro: It's a shiny new feature. We :heart: HTTPS

Con: It's not particularly "powerful" other than as a potential footgun for developers. It grants no new I/O capabilities.

**Comment by inexorabletash** [comment]
As [jochen said on blink-dev](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Jex3idOld48/68kPlGSeAwAJ):

"...it is just that the modern web only exists on secure contexts..."

So that's another Pro

**Comment by domenic** [comment]
I'd like to.

**Comment by jakearchibald** [comment]
https://groups.google.com/a/chromium.org/forum/#!msg/blink-api-owners-discuss/Gmxej1Ryj8c/djiqh8kMAAAJ

It doesn't feel like it should require HTTPS to me, but I'm not going to lose sleep over it.

**Comment by ralphch0** [comment]
One additional con: makes local testing and running local servers tedious.

**Comment by domenic** [comment]
No, local servers are secure contexts.

**Comment by inexorabletash** [comment]
I'm gonna make it so;. I've been convinced that the argument should be inverted: someone will have to argue convincingly that it should not be `[SecureContext]`
