### ISSUE TITLE
Spec in terms of parallel queues?

### ISSUE THREAD

**Issue by jakearchibald** [inexorabletash/web-locks#22]
https://html.spec.whatwg.org/multipage/infrastructure.html#parallel-queue

Parallel queues don't support "shared" steps yet, but that sounds like something that would be useful elsewhere.

(+@annevk in case he wants to veto this idea – shared steps could run in parallel with other shared steps, but non-shared steps must run exclusively)

**Comment by annevk** [comment]
I'm not sure I have enough context to judge the proposal. If non-shared steps must run exclusively it seems they need a parallel queue. Shared steps could run without one? Or can shared steps only run concurrently with other shared steps, but must still be exclusive from non-shared steps?

**Comment by jakearchibald** [comment]
> Or can shared steps only run concurrently with other shared steps, but must still be exclusive from non-shared steps?

Yep, that. Eg reads can happen in parallel. Writes must happen in series. Reads must wait for queued writes to complete.

**Comment by annevk** [comment]
In that case it sounds like you could invent a concept for doing multiple things in parallel and wait for them to complete. And you queue that on the parallel queue.

**Comment by annevk** [comment]
But yeah, maybe that should live in the HTML Standard too.

**Comment by inexorabletash** [comment]
I think this is done in the proto-spec.
