### ISSUE TITLE
Reserve system lock names

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/web-locks#29]
Per offline conversation with @slightlyoff

We may want to reserve a namespace for "system locks". For example, a lock could be auto-generated which a cache batch operation is being performed so that the completion can be observed.

One way to do this is to reserve a delimiter character in the lock names. (e.g. '-' or '`\x00`' or '🚦' or...). This would allow determination that such a lock was provided by the system.

Or we could use UUIDs. This would avoid restricting lock names, but then system locks could not be distinguished.

**Comment by ralphch0** [comment]
How would the UUID solution work across pages?

**Comment by annevk** [comment]
If we overloaded the strings with symbols that'd work.

**Comment by inexorabletash** [comment]
Note that I really haven't thought this through much yet. The one scenario I'm thinking of is generating a lock for cache batch operations, although on its own that's not useful (needs the ability to extend it, a way to observe completion, etc) I think there are (at least) two aspects to system-generated locks:

1. The system can generate locks that cannot be interfered with by user code. e.g. user code can't grab the "cache-foo" lock to prevent the cache named "foo" from being changed.
2. System locks can be distinguished from user created locks if reported by query(). (Locks objects returned by an API would implicitly be system locks - would they need to be obviously distinguished?)

> How would the UUID solution work across pages?

This satisfies point 1 since the user code can't guess a UUID. It would need extra logic to e.g. prevent "steal" from working. It would not satisfy point 2.

> If we overloaded the strings with symbols that'd work.

Definitely satisfies point 1. The details would require working through; these would not be well known symbols (unless we reified e.g. a localStorage lock across the origin...), so they would be symbols created within a particular agent. If we allow this only for system locks, then query() could either not report them or report... something, but it wouldn't be a useful Symbol. It could be useful to allow user code to specify Symbols as well (e.g. so a library's use of locks can be guaranteed to not be interfered with outside the library); again the question of what query() should do is interesting (how would the library self-diagnose?)

The symbol description could include the source (e.g. for a system-generated lock, indicate the API it came from.

(And if implementing this, I'd be tempted to implement via UUIDs behind the scenes.)

**Comment by inexorabletash** [comment]
Per offline discussion with @pwnall, let's go ahead and reserve `-` as a prefix character now.
