### ISSUE TITLE
Explainer note: Acquisition timeout without AbortController

### ISSUE THREAD

**Issue by pwnall** [inexorabletash/web-locks#31]
It's possible to do lock timeouts without an AbortController. I think that the same pattern can be used to implement any sort of cancelation in userland, with minimal overhead (there's an extra request floating around in memory for a bit more).

I'm tempted to conclude this means we could remove the dependency on AbortController, but I haven't reasoned through all the implications. Not having multiple resources means that the only observable difference (I can think of) is that shared lock requests may be blocked on a timed out exclusive request that would have been canceled. This observable difference goes away if we make lock resolution not be fair and grant shared locks asap, instead of considering the requests in queue order.

```js
function timeoutAcquire(resource, timeout, callback) {
  return new Promise((resolve, reject) => {
    let ranCallback = false;
    let timedOut = false;

    const timeoutHandler = setTimeout(() => {
      if (ranCallback)
        return;

      timedOut = true;
      reject(new Error(`Timed out while acquiring a lock on ${resource}`));
    }, timeout);

    const acquirePromise = navigator.locks.acquire(resource, (lock) => {
      if (timedOut)
        return;  // Release the lock immediately, if it was acquired.
      clearTimeout(timeoutHandler);

      ranCallback = true;
      resolve(acquirePromise);
      return callback(lock);
    });
  });
}
```

**Comment by ralphch0** [comment]
Isn't the AbortController meant to be used across a range of APIs for aborting? Is there an advantage to not depend on it, given the reduced verbosity and ease of transferable knowledge from other APIs? Personally as a developer, I would prefer to be able to abort a request and not have to think about the consequences of leaving a lock request hanging: Is it leaking memory? Is it making lock requests from other pages slower to be granted, ..etc.

**Comment by pwnall** [comment]
@ralphch0 Thanks for your feedback! These are very good points.

Advantage of not depending on AbortController -- First, a simpler spec would be easier to test and implement. This was my main motivation for bringing up the possibility here. Second, due to cross-team dependencies, I expect that we'd be able to ship a Chrome implementation for you to play with sooner if we can nix AbortController.

Leaking memory -- If a lock is actually held indefinitely, and you periodically do lock requests with timeouts, requests would queue up. AbortController would be a net benefit here.

Making other lock requests slower -- Assuming we don't get paged due to memory pressure, this approach should not slow things down. It's possible to implement the current API in O(1) amortized time per request, where the amortization is only due to the fact that releasing an exclusive lock can result in granting an unbounded number of shared lock requests.

**Comment by ralphch0** [comment]
I see, I was not aware that AbortController is not something that exists yet.
If we're going to remove the abort functionality (or delay it till the AbortController is implemented), then I would prefer at least having a timeout (in ms) option.

**Comment by domenic** [comment]
I think there's a lot of value in the platform using a single, predictable primitive for aborting, and would urge this proposal to continue to use AbortController.

**Comment by annevk** [comment]
AbortController is implemented in Firefox. We'd pretty strongly object to new specifications not using it, in particular if they offer other cancelation mechanisms (such as timeouts) that are not layered on top of it. In fact, I think it's best to leave timeouts to user land for now since we haven't really decided how we want to do them.

**Comment by pwnall** [comment]
We don't plan to build an alternative to AbortController into the locks API. I wanted to see if we can get away without any sort of cancelation in the API, and leave that to user land.

In the end, it turns out that we'll have AbortController pretty soon in Blink, so we can stick to our current plan.

Implementation concerns aside, IMHO, since this is a low-level API, every bit of it should be subjected to the same analysis -- "is this really necessary, or can it be built on top of the API?" I think that @ralphch0's observation about memory leaks is a good argument for the necessity of AbortController.

**Comment by annevk** [comment]
Sure, we left out cancelation from `fetch()` v0. I'm just saying that if you need any kind of cancelation, that's the way to go as the low-level primitive.
