### ISSUE TITLE
Nested acquisitions?

### ISSUE THREAD

**Issue by ralphch0** [inexorabletash/web-locks#33]
Just wondering what should happen if one client tries to acquire the same lock multiple times.
Should it be automatically granted? Or should it block on releasing the first lock? In the current implementation, it's the latter (unless this is a bug).

Example: (below would cause a deadlock)
```
await navigator.locks.acquire('mylock', async lock => {
    await navigator.locks.acquire('mylock', async lock => {
        return 1;
    });
});
```

The argument for granting is to avoid keeping track that the lock is acquired and avoid deadlocks like the example above. The argument for blocking, is that it would allow libraries running on the same page to also coordinate using this API.

**Comment by inexorabletash** [comment]
The intention is blocking (which matches the proto-spec and as you note the implementation in Chrome). 

I'll add something to the Explainer.

**Comment by inexorabletash** [comment]
Closing this out since it was documented.
