### ISSUE TITLE
Racing aborts and requests

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/web-locks#34]
Consider this, assuming the lock is grantable:

```js
const controller = new AbortController();
const p = navigator.locks.acquire(res, {signal: controller.signal}, callback);
controller.abort();
```

* Does `callback` run or not?
* Does `p` resolve or reject?

From one perspective: the controller has synchronously aborted before the callback runs, so why would the callback run?

From another: the abort lags the request headed to the lock manager so the request should be granted; the abort is "too late"

The latter "naturally" falls out of the spec algorithms (and initial implementation in Chrome). But the former is possible, and would be implemented by dropping the lock immediately if the abort is signaled before the response is delivered to script.

**Comment by ralphch0** [comment]
>> From another: the abort lags the request headed to the lock manager so the request should be granted; the abort is "too late"
Shouldn't we be racing the abort (locally) with the lock **response** (not request)? Meaning that regardless of this scenario which seems a bit unusual, when I call abort() I would expect either the callback to be called or acquisition to reject as soon as possible (whatever won the race). I think the main concern here is that once abort is called there should be no additional delay. Whether this scenario calls the callback or rejects, maybe that doesn't need to be spe'ced out (given that it's kind of pathological)?

**Comment by inexorabletash** [comment]
"race" might not be the right term to use... and hrm, it's more subtle than I thought.

As currently specified here's how it works:
* the request turns into a set of steps (A) added to run on the "lock task queue"
* the abort signals
* the steps (A) run, including these relevant parts:
  * if `ifAvailable` is specified and the lock is not available, request fails. done
  * the request is added to the request queue (in the "steal" case it's just prepended)
  * a signal handler is added to remove the request from the request queue
  * the request queue is processed

So it depends when the signal handler is processed for an already signalled controller  - synchronously or async?

**Comment by inexorabletash** [comment]
In an implementation like Chrome, it looks more like:

* the request call is made in; an IPC is sent to the back-end to request the lock
* the signal comes in; an IPC is sent to the back-end to cancel the request
* the back end sees the IPC request, and grants it; an IPC is sent to the front-end to deliver the lock
* the back end sees the IPC signal, and ignores it (since the request was already granted)
* the front-end receives the IPC with the lock, and grants it to script

(Note that this is roughly equivalent to the above, assuming the signal handler process is async.)

The implementation could, at the end, note that the abort was signalled and drop the lock, and notify script that the request was aborted instead. 

...

Agreed that this is pathological so we don't need to think too hard about it, but it's script-visible so we need to decide and spec and test it.

**Comment by inexorabletash** [comment]
Aligned spec with implementation here. 

* If the abort signals before the **response** has come back, the promise settles immediately (AbortError) and the client side of the request is dropped. If the back end had granted the request and the lock was in flight it is dropped on the floor.
* If the abort signals after the **response** has come back, it is ignored (the promise has already settled, and there's no request to drop)

**Comment by ralphch0** [comment]
> If the back end had granted the request and the lock was in flight it is dropped on the floor.
"Dropped on the floor" still entails releasing the granted lock, correct?

**Comment by inexorabletash** [comment]
> "Dropped on the floor" still entails releasing the granted lock, correct?

Yes!

(Thanks for sanity checking my imprecise language.)
