### ISSUE TITLE
Question about design of API... 

### ISSUE THREAD

**Issue by marcoscaceres** [inexorabletash/web-locks#38]
Just wondering, how come you went with taking a function as the second argument instead of having the `lock` returned in the promise? That is, why?

```JS
async function get_lock_then_write() {
  await navigator.locks.request('resource', async lock => {
    await async_write_func();
  });
}
```

Instead of just?:

```JS
async function get_lock_then_write() {
  const lock = await navigator.locks.request('resource');
  await async_write_func();
  // do whatever to release the lock later... 
}
```

If you stick with the current design, the `request()` overload methods of `LockManager` seem a bit odd (having an optional argument in the middle of a method is not great)... why not just do:

```JS
  Promise<any> request(DOMString name,
                       LockGrantedCallback callback,
                       optional LockOptions options);
```

**Comment by marcoscaceres** [comment]
(fixed couple of typos above)

**Comment by inexorabletash** [comment]
> how come you went with taking a function as the second argument instead of having the lock returned in the promise ... ?

We started with such a design where the lock object was returned and required an explicit release, and evolved from there as footguns were noted. Best captured in the discussion at: https://github.com/inexorabletash/web-locks/issues/9

> having an optional argument in the middle of a method is not great

This is explcitly covered in the explainer in the FAQ, search for _"Why is the options argument not the last argument?"_

Discussed at https://github.com/inexorabletash/web-locks/issues/19

**Comment by marcoscaceres** [comment]
Ok, but the optional argument in the middle of the overload seems to be in the proto-spec. Domenic pointed that out too. It seems it didn’t get fixed.

**Comment by marcoscaceres** [comment]
In #9, I don’t really understand how it leads to the current design with respect to having a promise returned that resolves to “any”, plus taking the callback as the second argument that eventually gets a lock. That still seems super weird to me (it might be fine, it’s just odd). 

I guess my core question is: why does the returned promise resolve with “any”? What is that used for:

```js
// what do I do with aThing?
const aThing = await navigator.locks.request('resource', f);
```

**Comment by inexorabletash** [comment]
Dominic advocated for options in the middle. That was how the discussion concluded. 

The outer promise resolves with the result of the callback. Could also resolve with void

**Comment by inexorabletash** [comment]
Oh, "optional" on the overload in the proto-spec is wrong. Position is correct, though.

**Comment by inexorabletash** [comment]
I kept reading "optional argument" as "options argument". My bad. Will fix when I have a bigger screen and a real keyboard.

**Comment by inexorabletash** [comment]
Apologies for the delay...

> I guess my core question is: why does the returned promise resolve with “any”? 

```js
const result = await navigator.locks.request('resource', async lock => {
   let ok = await do_something();
   if (ok) {
     ok = await do_something_else();
   }
   return ok;
});
```

When the `result` promise resolves (1) the callback function has completed, (2) the lock has been released and (3) it has the value of `ok`

We could make `request()` resolve to `Promise<void>` instead, but it seemed like plumbing the return value of the callback out made sense, rather than dropping it on the floor. If it resolved to `Promise<void>`, the return value could be smuggled out with a local variable. 

In addition, if the callback throws then the `result` Promise is a rejection, e.g. you can code like this:

```js
try {
  await navigator.locks.request('resource', async lock => {
    if (!await do_something()) throw Error();
    if (!await do_something_else()) throw Error();
  });
} catch (ex) { ... }
```

or if `do_something()` and friend throw on error, just:

```js
try {
  await navigator.locks.request('resource', async lock => {
    do_something();
    do_something_else();
  });
} catch (ex) { ... }
```

**Comment by marcoscaceres** [comment]
I don't know... that still seems weird to me... like the API is overstepping. Consider, if I want the `ok` value, then I can just add a promise: 

```JS
function getTheLock() {
  return new Promise(resolve => {
    navigator.locks.request("resource", async lock => {
      let ok = await do_something();
      if (ok) {
        ok = await do_something_else();
      }
      resolve(ok);
    });
  });
}
```

But even then I hold the problem is the current design doesn't feel idiomatically. Specially when this is cleaner (and includes the error handling): 

```JS
async function getTheLock(type) {
  const lock = await navigator.locks.request(type);
  let ok = false;
  ok = await do_something();
  if (ok) {
    ok = await do_something_else();
  } else {
    throw new Error();
  }
  return ok;
}
```

You get all the same benefits, and way less nesting, no?

**Comment by ralphch0** [comment]
In the first snippet, you still need to handle the rejection case. Also, by calling the resolve method within the callback, you would be resolving the outer promise before the lock is released.

Isn't propagating the resolve/reject values very similar to the then() method of promises? Seems like a natural pattern when we want a method to control an async operation: start it, catch errors, and return the result of the operation.

**Comment by domenic** [comment]
Your second snippet also never releases the lock, even on the success path.

**Comment by marcoscaceres** [comment]
> Your second snippet also never releases the lock, even on the success path.

Sure, but wouldn’t that just be:

```js
return {ok, lock};
```

Then the caller can release the lock? I’m obviously missing something here which is non-obvious... if I’m not getting it, it’s pretty likely other developers will  misunderstand it too, which worries me.

**Comment by domenic** [comment]
You shouldn't push the responsibility of releasing the lock on to the caller. It's an implementation detail of your function that uses the lock, in most cases. The caller generally doesn't care that the resource your function is manipulating is locked at all.

Also your return version will permanently fail to release the lock if any of the function's steps throw an exception.

**Comment by marcoscaceres** [comment]
Ah, ok. Think I get it now (and also why it’s a callback). Thanks @domenic!

**Comment by inexorabletash** [comment]
@marcoscaceres - any suggestions for how we do a better job in the explainer (readme) of explaining this?

**Comment by marcoscaceres** [comment]
Any plans to move this to WICG or WHATWG? Also, please let me know if you want more Mozilla folks to look at this and maybe [take a position on it](http://github.com/mozilla/standards-positions/)... personally speaking, I'd say it's definitely "worth prototyping".

**Comment by inexorabletash** [comment]
I proposed this as a WICG topic. Waiting for. +1 from another interested member. Hint hint....

**Comment by inexorabletash** [comment]
And "yes please" to more eyeballs from Mozilla.

**Comment by inexorabletash** [comment]
Also, thanks for all the suggestions on the abstract. I'll work those in. I have to put a blog post together as well, and it's a very useful structure.

**Comment by marcoscaceres** [comment]
Ok, request sent https://github.com/mozilla/standards-positions/issues/64 

You might want to subscribe to that. If no-one responds, I can reach out to a few people.
