### ISSUE TITLE
Lock vs LockInfo

### ISSUE THREAD

**Issue by ralphch0** [inexorabletash/web-locks#42]
According to the spec the request() method returns a Lock object, while the query() method returns LockInfo objects. The only difference is the clientId field. 
https://inexorabletash.github.io/web-locks/#api-lock-manager

Is there are reason why we have this differentiation?

**Comment by inexorabletash** [comment]
LockInfo is a dictionary because it's a pure information dump. Lock is an interface because I imagine adding more capabilities in the future, e.g. event for when it is released, waitUntil, etc.

I agree there's no reason to have Lock be an interface now, but it's hard to change later.

**Comment by ralphch0** [comment]
Makes sense. Any reason clientId shouldn't also be on the Lock object.

**Comment by inexorabletash** [comment]
It's not really beneficial now since any given script is going to get locks corresponding to its own context. If we expose the environment id as e.g. `window.environmentId`, then that would be the same for all locks visible to a script. (Unless there are cross-window hijinks.)

**Comment by inexorabletash** [comment]
Can you comment on https://github.com/whatwg/html/issues/3378 perchance?

**Comment by inexorabletash** [comment]
Per offline discussion, we should push on exposing it globally rather than having web apps "abuse" locks to determine the page's id.
