### ISSUE TITLE
What are the benefits of shared locks?

### ISSUE THREAD

**Issue by umaar** [inexorabletash/web-locks#46]
Trying to understand the benefits/use cases of shared locks? Holding an exclusive lock makes sense, but what are some use cases for shared locks?

Maybe coordinating workloads across various tabs?

**Comment by umaar** [comment]
Thanks for explaining!

**Comment by inexorabletash** [comment]
And just to clarify further (now that I'm not on a train going into a tunnel): individual APIs like Indexed DB or some future filesystem API may support the reader/writer pattern directly, but the locks API lets you compose such work across such APIs, and with APIs that don't directly support the pattern.

See also: https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock
